## About the UI, build, services
---
package:
  name: about
  title: About Panel
  description: A package containing the about panel
  type: legacy
services:
  route:
    routes:
      - path: "{{name}}"
        component: views/About
      - path: "{{name}}/build"
        component: views/AboutBuild
      - path: "{{name}}/services"
        component: views/AboutServices
      - path: "{{name}}/plugins"
        component: views/AboutPlugins
  menu:
    items:
      - name: about
        type: internal
        path: "{{name}}"
        label: About
        icon: info-circle
      - name: about-build
        type: internal
        path: "{{name}}/build"
        label: About the UI Build
        icon: building-o
      - name: about-services
        type: internal
        path: "{{name}}/services"
        label: KBase Services Status
        icon: server
      - name: about-plugins
        type: internal
        path: "{{name}}/plugins"
        label: KBase UI Plugins
        icon: plug
