---
name: Build and Push Up Develop Branch Image
"on":
  push:
    branches:
      - develop
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v2
      - name: Build and Push to Packages
        if: github.event.pull_request.draft == false
        env:
          BUILD: ci
          # PR: "${{ github.event.pull_request.number }}"
          # SHA: "${{ github.event.pull_request.head.sha }}"
          # DOCKER_ACTOR: "jsfillman"
          # DOCKER_TOKEN: "${{ secrets.GHCR_TOKEN }}"
        run: "./.github/workflows/scripts/build-push-develop.sh\n"
