---
name: Build and Push Up Develop Branch Image
on:
  push:
    branches:
      - develop
# env:
#   BUILD: ci
#   VCS_REF: ${{ github.sha }}
#   BRANCH: ${{ github.ref }}
#   TAG: ${{ github.ref }}
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # hmm, try this.
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          build-args: |
            BUILD_CONFIG=ci
            BUILD_DATE=${{ steps.date.outputs.date }}
            VCS_REF=${{ github.sha }}
            BRANCH=${{ github.ref }}
            TAG=${{ github.ref }}
          tags: ghcr.io/${{ github.repository_owner }}/kbase-ui:develop
